### ISSUE TITLE
Errors when opening or accessing a Borehole

### ISSUE THREAD

**Issue by sorghumking** [alt-lu/pywellcad#131]
I'm new to pywellcad and tried the README.md sample code:

```
import wellcad.com

app = wellcad.com.Application()
sample_file_path = r"C:\Program Files\Advanced Logic Technology\WellCAD\Samples\Classic Sample.wcl"
borehole = app.open_borehole(sample_file_path)
gr_log = borehole.get_log("GR")
gr_log.file_export(r"C:\Temp", "sample_gr", "csv")
```

After entering the the `borehole = ` line, the document opens correctly in WellCAD.  However, I get the following errors:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xander\AppData\Local\Programs\Python\Python39\lib\site-packages\wellcad\com\_application.py", line 104, in open_borehole
    return Borehole(self._dispatch.OpenBorehole(path))
  File "C:\Users\xander\AppData\Local\Programs\Python\Python39\lib\site-packages\wellcad\com\_dispatch_wrapper.py", line 53, in __init__
    self._dispatch._FlagAsMethod(method_name)
  File "C:\Users\xander\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\dynamic.py", line 543, in _FlagAsMethod
    details = build.MapEntry(self.__AttrToID__(name), (name,))
  File "C:\Users\xander\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\dynamic.py", line 551, in __AttrToID__
    return self._oleobj_.GetIDsOfNames(0, attr)
pywintypes.com_error: (-2147352570, 'Unknown name.', None, None)
```

Because of the error, no `Borehole` object is returned, which makes it difficult to further explore the capabilities of the API.

I see the same behavior on `app.get_borehole()` and `app.get_active_borehole()` calls.

I see the errors in both Python 3.9 and 3.10.  I'm running the Python interpreter in PowerShell.  WellCAD 5.6 build 1028.

Is there a workaround for this?

**Comment by m-schubert** [comment]
It looks like it was broken by commit 81ba790. If I had to guess, it was adding the extra dispatch methods in preparation for v5.7 WellCAD release.

@ArnaudCrl, can you please look into this? Let's handle the exceptions when we register attributes/methods in `DispatchWrapper`.
