### ISSUE TITLE
Error when running sample code

### ISSUE THREAD

**Issue by slbin** [alt-lu/pywellcad#134]
Dear developer,

When I run the sample code I got error below, would you please shed some light on this?

```
Traceback (most recent call last):
  File "C:\Users\klif\Documents\WellCAD\code\converter\converter.py", line 5, in <module>
    borehole = app.open_borehole(sample_file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klif\Documents\WellCAD\code\.venv\Lib\site-packages\wellcad\com\_application.py", line 104, in open_borehole
    return Borehole(self._dispatch.OpenBorehole(path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klif\Documents\WellCAD\code\.venv\Lib\site-packages\wellcad\com\_dispatch_wrapper.py", line 53, in __init__
    self._dispatch._FlagAsMethod(method_name)
  File "C:\Users\klif\Documents\WellCAD\code\.venv\Lib\site-packages\win32com\client\dynamic.py", line 543, in _FlagAsMethod
    details = build.MapEntry(self.__AttrToID__(name), (name,))
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klif\Documents\WellCAD\code\.venv\Lib\site-packages\win32com\client\dynamic.py", line 551, in __AttrToID__
    return self._oleobj_.GetIDsOfNames(0, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352570, 'Unknown name.', None, None)
```

**Sample code from github README**
```
import wellcad.com
app = wellcad.com.Application()
sample_file_path = r"C:\Program Files\Advanced Logic Technology\WellCAD\Samples\Classic Sample.wcl"
borehole = app.open_borehole(sample_file_path)
gr_log = borehole.get_log("GR")
gr_log.file_export(r"C:\Temp", "sample_gr", "csv")
```

**Comment by m-schubert** [comment]
Apologies. We made a change in pywellcad v0.2.0 that broke compatibility with WellCAD v5.6. A fix has been implemented (#133), but we haven't yet released a patch version. This will occur in the next couple of days.

For now, I'd recommend reverting to v0.1.0 (`pip install 'pywellcad==0.1.0' --force-install`).
