### ISSUE TITLE
data_min raises pywintypes.com_error on Image Log

### ISSUE THREAD

**Issue by brocktimus** [alt-lu/pywellcad#155]
This code:

```
import wellcad.com
import os
import json

channel_path = "OBI Image"

app = wellcad.com.Application()
sample_file_path = r"C:\Program Files\Advanced Logic Technology\WellCAD\Samples\OBI 2G Color Classification.wcl"
borehole = app.open_borehole(sample_file_path)
log = borehole.get_log(channel_path)
print(log.data_min)
```

Results in:

```
Traceback (most recent call last):
  File "Z:\data-generation\src\image.py", line 17, in <module>
    print(log.data_min)
          ^^^^^^^^^^^^
  File "C:\Users\Brock\AppData\Local\Programs\Python\Python312\Lib\site-packages\wellcad\com\_log.py", line 109, in data_min
    return self._dispatch.DataMin
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brock\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32com\client\dynamic.py", line 627, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352567, 'Exception occurred.', (1, 'WellCAD', 'The property or the method is not allowed on this instance of the object.', 'C:\\Program Files\\Advanced Logic Technology\\WellCAD\\Program\\WellCAD.CHM', 393576, 0), None)
```

**Comment by brocktimus** [comment]
This is possibly a false report, I'm not sure if this has ever been supported against this log type.

**Comment by m-schubert** [comment]
Yeah, this is expected behaviour. The `data_min` property is only valid for well, mud and interval logs according to the documentation:

> *property*
> `data_min`
> The minimum data value of the Well, Mud or Interval Log.

I'll close this.
